### ISSUE TITLE
RPC signing (eth_sign) functionality and HD vault support

### ISSUE THREAD

**Issue by tymat** [se3000/ruby-eth#10]
I've created a fork on https://github.com/digixglobal/ruby-eth which adds some extra functionality such as RPC signing similar to web3.eth.sign and HD vault support.

https://github.com/digixglobal/ruby-eth  

Let me know if this is something you'd like and I can submit a PR

### HD Vaults

This branch adds HD wallet functionality which can be seeded with Trezor style mnemonic words.

```ruby
# Create a new vault
v = Eth::Vault.new
key = v.get_key(1)

# Restore a vault from a mnemonic
v = Eth::Vault.new(secret_seed_phrase: "trouble mesh impact indoor inquiry aim index deposit weekend alter pottery chef eye page elder awesome paper sport arch illegal muscle another blossom arctic")
key = v.get_key(2)

# Specify an HD Root Path (see: https://github.com/ethereum/EIPs/issues/84)

v = Eth::Vault.new({secret_seed_phrase: "trouble mesh impact indoor inquiry aim index deposit weekend alter pottery chef eye page elder awesome paper sport arch illegal muscle another blossom arctic"}, "m/44'/60'/0'/0/0")
key = v.get_key

```

### web3.eth.sign functionality

You can sign arbitrary messages which can be verified on the EVM using ecrecover.

```
v = Eth::Vault.new
signer = Eth::RpcSigner.new(v.get_key)
a = signer.sign_message('foobar')
```

**Comment by se3000** [comment]
Apologies for the slow response.

This looks great, thanks. I'd love to get some tests for it before pulling it in though, any chance you would write those? I can do it, but it will take me a little while to get to it.

Thanks again!

**Comment by mhluska** [comment]
Are there any updates on this? I'd love to use this.

**Comment by se3000** [comment]
Which part? HD keys or RPC signing?

**Comment by mhluska** [comment]
@se3000 I meant HD keys. I tried using your fork but ran into some issues. I ended up solving the issue like this: https://ethereum.stackexchange.com/a/34520/26695

Please let me know if you see any issues with that approach.

**Comment by se3000** [comment]
Good to know. Tests are the big blocker on this PR, ideally I'd change the API a bit too.

Unfortunately I won't have the time to implement this for a while. I'd be happy to accept a PR if had tests that offered assurance that bugs, like the one you discovered, don't exist.

As for sweeping funds, it depends on how you implemented your logic to pick which keys are used to accept payment. Figuring out [which addresses have been paid](https://bitcoin.stackexchange.com/a/54664/18506) is typically the hard part. Once you know that, sending transactions from that address should be relatively easy(and supported by this gem).
