### ISSUE TITLE
hex_data for creating a new transaction

### ISSUE THREAD

**Issue by iscott** [se3000/ruby-eth#11]
I want to build a new transaction. What is the hex_data I need to provide?

```
tx = Eth::Tx.new({
  data: hex_data,
  gas_limit: 21_000,
  gas_price: 3_141_592,
  nonce: 1,
  to: key2.address,
  value: 1_000_000_000_000,
})
```

**Comment by se3000** [comment]
Are you sending any data in the transaction? If you just want to transfer ether, than you can just make the `data` attribute an empty string.

**Comment by se3000** [comment]
Requiring an empty string instead of just allowing it to be null is not a great experience. On my list of things to improve is adding sane defaults for new transactions.

**Comment by se3000** [comment]
No reply. Closing. Feel free to reopen with more details.
