### ISSUE TITLE
Getting the error while creating a transaction

### ISSUE THREAD

**Issue by superrordev** [se3000/ruby-eth#13]
Creating a transaction like this:
`tx = Eth::Tx.new({
  data: hex_data,
  gas_limit: 21_000,
  gas_price: 3_141_592,
  nonce: 1,
  to: key2.address,
  value: 1_000_000_000_000,
})`

When running the code, getting this error:
**ArgumentError: wrong number of arguments (given 2, expected 1)**

I'm not sure why. Please check it.

**Comment by se3000** [comment]
The only errors I get when running that line are undefined variable errors. When I define those variables, everything works. Closing this, but feel free to open with more detail on how to reproduce.
