### ISSUE TITLE
Does not load on Heroku

### ISSUE THREAD

**Issue by gsdean** [se3000/ruby-eth#17]
LoadError: Could not open library '/usr/lib/ssl': /usr/lib/ssl: cannot read file data: Is a directory.

**Comment by se3000** [comment]
I believe this is a change in Heroku's newest stack. It'd be great to support it long term, but that's going to take some time to investigate and test out.

If you need this immediately on Heroku you can use the [cedar-14 stack](https://devcenter.heroku.com/articles/stack).

**Comment by gsdean** [comment]
did a more little digging, seems like this might be an ffi issue
https://github.com/ffi/ffi/issues/595

**Comment by hstove** [comment]
I got this working on Heroku with https://github.com/GemHQ/money-tree/pull/28

**Comment by se3000** [comment]
Just pushed version 0.4.7, with the new version of MoneyTree. I ran a quick test on heroku and it appears to work on the current default stack, heroku-16. I'm going to close this, but feel free to reopen if you run into other issues.

**Comment by starwels** [comment]
Hey guys. It is not working on heroku-18 and heroku-20. Here is the log from my heroku server. I tried both heroku-18 and heroku-20

`
Could not open library 'libssl.so.10': libssl.so.10: cannot open shared object file: No such file or directory.
Could not open library 'libssl1.0.0': libssl1.0.0: cannot open shared object file: No such file or directory.
Could not open library 'libssl1.0.0.so': libssl1.0.0.so: cannot open shared object file: No such file or directory.
Could not open library '/usr/lib/ssl': /usr/lib/ssl: cannot read file data: Is a directory.
Could not open library 'libssl.so': libssl.so: cannot open shared object file: No such file or directory
`

**Comment by q9f** [comment]
Hi @starwels - this is going to be fixed with the next release of `money-tree` and `eth` gems. please subscribe to
* https://github.com/se3000/ruby-eth/pull/66
* https://github.com/GemHQ/money-tree/pull/43

to get notified once it's merged.
