### ISSUE TITLE
Support for OpenSSL 1.1.0f

### ISSUE THREAD

**Issue by thellimist** [se3000/ruby-eth#27]
When will this be supported?

**Comment by 5hanth** [comment]
+1

**Comment by thellimist** [comment]
For those who have issues with openssl version they can use the following to downgrade openssl version to 1.0.2

```
FROM ruby:2.5.1

# Remove OpenSSL
RUN rm /usr/bin/openssl
RUN rm -r /usr/include/openssl
RUN rm /usr/share/man/man1/openssl.1ssl.gz

# Install OpenSSL 1.0.2o
WORKDIR /opt
RUN wget https://www.openssl.org/source/openssl-1.0.2o.tar.gz
RUN tar -xzvf openssl-1.0.2o.tar.gz
RUN rm openssl-1.0.2o.tar.gz
RUN mv /opt/openssl-1.0.2o /opt/openssl
WORKDIR /opt/openssl
RUN ./config
RUN make install
RUN ln -sf /usr/local/ssl/bin/openssl /usr/bin/openssl
RUN ln -nfs /usr/lib/x86_64-linux-gnu/libssl.so.1.0.2 /usr/lib/x86_64-linux-gnu/libssl.so

# Your code comes next
```

**Comment by se3000** [comment]
Can someone make a PR for this. I imagine you have to update [this line](https://github.com/se3000/ruby-eth/blob/master/lib/eth/open_ssl.rb#L11), but I'm not entirely sure what it takes and don't know if I'll be able to verify that it works.

Thanks!

**Comment by etscrivner** [comment]
It appears that OpenSSL 1.1.0 completely changed the way the library is initialized. I've opened #42 which I've tested against OpenSSL 1.0.0 and OpenSSL 1.1.0. It adds a check on the library version before performing initialization to ensure that it calls the correct initialization method(s).
