### ISSUE TITLE
Giving attribution to original work

### ISSUE THREAD

**Issue by ticklemynausea** [se3000/ruby-eth#29]
Hi! Sorry that I'm opening an issue for this.

We needed a ruby library to validate and generate eip55 checksums, so we extracted the relevant code and tests into [ruby-eip55](https://github.com/FractalBlockchain/ruby-eip55), since we did not need most of the features `ruby-eth` offers.

We kept the original license, credited the original project in the README and left the original authors in the gem spec.

This might be enough, but still we felt we should ask if you want any other way to give attribution to the original project?

Thanks

**Comment by se3000** [comment]
Looks good to me. Thanks for the heads up!
