### ISSUE TITLE
signing does not support large chain IDs

### ISSUE THREAD

**Issue by escoffon** [se3000/ruby-eth#31]
The attached file eip_issue.txt has a more complete writeup, but essentially if the chain ID is large enough (>120), transactions are signed incorrectly. The problem is that the code in tx.rb and open_ssl.rb packs the signature's v value as a one-byte field, and if EIP-155 support is enabled, a chain ID larger that 119 or 120 overflows and only the low byte is packed.

I have a fix for this, but unfortunately it involves a breaking change. Basically, I took the Web3 approach and moved the chain ID field into the transaction object (and got rid of chain_id in the configuration). This encapsulates tx behavior in the instances, instead of relying on the external chain ID. It also makes it possible to manage tx objects from different chains.

The open_ssl.rb code only sees plain ECDSA signatures (where v is 27 or 28), so all is good. The tx object manages modifications to v when the transaction is serialized (Eth::Tx.hex in our case). One could argue that EIP-155 strictly speaking does not define a "new" signature type, but rather embeds the chain ID in the v value for use by clients to prevent replay attacks. (I am one.) Therefore, signing and recovering should be based on the plain ECDSA signature, and the EIP-155 version be used only when serializing and deserializing.

I will create a pull request with my modifications.

[eip_issue.txt](https://github.com/se3000/ruby-eth/files/2308282/eip_issue.txt)

**Comment by se3000** [comment]
Your fix has been included in v0.4.9. Thanks!
