### ISSUE TITLE
Class error when deploying to heroku

### ISSUE THREAD

**Issue by mvanh** [se3000/ruby-eth#33]
superclass mismatch for class Digest::SHA3 (Digest::Class is given but was Digest::Base) when used in a project and deployed to heroku

**Comment by se3000** [comment]
What version of ruby are you using?

**Comment by se3000** [comment]
I need to investigate more, but I believe that this is an error with the sha3 repo. I believe that it no longer works with ruby 2.5+. Looks like that repo is unmaintained, so we'll probably have to fork it... probably going to take some time. I think the best immediate workaround is to switch to ruby 2.4.

**Comment by mvanh** [comment]
Ok - thanks so much - i'll try and switch to ruby 2.4 and see what happens. Will let you know 

http://about.me/mvanh

Sent via Superhuman ( https://sprh.mn/?vip=mvh@lokigroup.com )

**Comment by se3000** [comment]
As [mentioned here](bundle config build.digest-sha3 --with-cflags="-Wno-format-security"), there is a workaround that you can add to your Gemfile:
```ruby
git 'https://github.com/izetex/digest-sha3-ruby' do
  gem 'digest-sha3'
end
```

I've verified the above works on the latest Heroku stack, heroku-18. Alternatively, if you're just building locally and not deploying to Heroku, you can run `bundle config build.digest-sha3 --with-cflags="-Wno-format-security"` before running `bundle install`.

**Comment by se3000** [comment]
Closing this for now. Feel free to reopen if you run into it.
