### ISSUE TITLE
version 0.4.9 missing from rubygems

### ISSUE THREAD

**Issue by wojtczal** [se3000/ruby-eth#38]
Hey! For some reason the 0.4.9 version has been yanked from rubygems 😢 (https://rubygems.org/gems/eth/versions). any particular reason for removing it?

**Comment by se3000** [comment]
Yeah, it had a [breaking change](https://github.com/se3000/ruby-eth/pull/32#commitcomment-30815002) for some dependent libraries, to avoid other people pulling that in and getting errors [it was yanked](https://github.com/se3000/ruby-eth/pull/37#issuecomment-428460990).

Feel free to reopen if there was anything you specifically needed in it, but v0.4.10 should be functionally equivalent.
