### ISSUE TITLE
Implement EIP712 support for signTypedData

### ISSUE THREAD

**Issue by rstormsf** [se3000/ruby-eth#44]
feel free to reference 
https://github.com/AztecProtocol/aztec-crypto-js/blob/master/eip712/eip712.js

https://github.com/MetaMask/eth-sig-util/blob/master/index.js#L438

**Comment by shideneyu** [comment]
+1

**Comment by q9f** [comment]
Will be included in release 0.5.0, ref https://github.com/q9f/eth.rb/pull/27
