### ISSUE TITLE
How do you verify personal_sign?

### ISSUE THREAD

**Issue by patrick99e99** [se3000/ruby-eth#51]
```
key.verify_signature msg, key.sign(msg)
=> true
```

but

```
key.verify_signature msg, key.personal_sign(msg)
=> false
```

What steps need to be taken to verify a signature made from `personal_sign`?

**Comment by sg552** [comment]
Yes, can not verify. 
My signed tx is ignored by my ETH node, without any reason or debug clue.

I gave up and turn to NODE version, refer to: https://medium.com/blockchain-musings/how-to-create-raw-transactions-in-ethereum-part-1-1df91abdba7c

Really hope there is stable Ruby version for ETH operations

**Comment by q9f** [comment]
check out https://github.com/q9f/ethereum-on-rails

`personal_sign` can only be validated with `personal_recover`

https://github.com/q9f/ethereum-on-rails/blob/main/app/controllers/sessions_controller.rb#L44

however, `personal_recover` returns a public key belonging to an ethereum account that signed the message.

so if the recovered account matches the account that claims to have signed the message, consider it signed.

```ruby
signature_pubkey = Eth::Key.personal_recover message, signature
signature_address = Eth::Utils.public_key_to_address signature_pubkey

if user_address.downcase.eql? signature_address.downcase
  # => signature is valid
end
```

we could wrap that in some function.

**Comment by q9f** [comment]
starting from version 0.5.0, you can just call 

```ruby
Eth::Signature.verify(blob, signature, public_key, chain_id)
```

and it will try to match the type of data you pass according to EIP 191 or 712.

ref https://github.com/q9f/eth.rb/pull/27
