### ISSUE TITLE
require "eth" aborts irb / rails server on 2.7.2p137

### ISSUE THREAD

**Issue by 5hanth** [se3000/ruby-eth#54]
```
✗ irb
2.7.2 :001 > require "eth"
[1]    91953 abort      irb
➜  app git:(main) ✗ ruby -v
ruby 2.7.2p137 (2020-10-01 revision 5445e04352) [x86_64-darwin19]
```

**Comment by k0shima** [comment]
@5hanth 
try this
https://github.com/se3000/ruby-eth/issues/47#issuecomment-610965751

**Comment by 5hanth** [comment]
apparently, I was never able to use `ruby-eth` and wrote a coin manager (node.js) that runs independently with private keys of hot wallet that solely takes requests from the app server in a VPC.

**Comment by q9f** [comment]
duplicate of #47
