### ISSUE TITLE
It always happen a error with openssl,my openssl is 1.0.2t.

### ISSUE THREAD

**Issue by bocai-h** [se3000/ruby-eth#55]
FFI::NotFoundError (Function 'OPENSSL_init_ssl' not found in [libssl.dylib])

**Comment by q9f** [comment]
Please try this: https://github.com/se3000/ruby-eth/issues/47#issuecomment-609020317

> So after a long research, I think I solved the problem. For some reason linking without versioning is not possible anymore:
> 
> > Clients should not load the unversioned libssl dylib as it does not have a stable ABI.
> > So I had openssl1.1
> 
> Steps to fix:
> 
>     1. brew update & brew upgrade & brew install openssl
> 
>     2. cd in your openssl lib folder in my case: usr/local/opt/openssl@1.1/lib
> 
>     3. copy files in /usr/lib:
>        sudo cp libssl.1.1.dylib  libcrypto.1.1.dylib /usr/local/lib/
> 
>     4. make softlink
>        sudo ln -s libssl.1.1.dylib libssl.dylib
>        sudo ln -s libcrypto.1.1.dylib libcrypto.dylib
> 
> 
> Hope I could help you.
