### ISSUE TITLE
Support for ruby 3?

### ISSUE THREAD

**Issue by rwehresmann** [se3000/ruby-eth#57]
I'm using ruby 3.0.1, and `gem install eth` is resulting in:

```
ERROR:  While executing gem ... (NoMethodError)
    undefined method `request' for nil:NilClass
```

**Comment by giannadakis** [comment]
I have the same problem.

**Comment by rwehresmann** [comment]
The problem is this dependency: https://github.com/se3000/ruby-eth/blob/develop/eth.gemspec#L22

[digest-sha3-patched](https://github.com/teamhedge/digest-sha3-ruby/blob/master/digest-sha3-patched.gemspec) is requiring ruby `~> 2.2`.

**Comment by bleedr** [comment]
I've modified the dependency, then it works, considering this change:

https://github.com/se3000/ruby-eth/issues/47#issuecomment-610965751

**Comment by nitsujri** [comment]
Thanks @bleedr and @rwehresmann. Between the two of you I got the package running on ruby3.

1. https://github.com/sydneyitguy/digest-sha3-ruby/tree/patch-1
    ```
    gem 'digest-sha3-patched', github: 'sydneyitguy/digest-sha3-ruby', ref: '517f1941bd6be6a28f8cc16e3dd72e4171fec6fa'
    gem 'eth'
    ```
2. From same thread, further down: https://github.com/se3000/ruby-eth/issues/47#issuecomment-810929223
    ```
    sudo mkdir /usr/local/lib/
    sudo ln -s $(brew --prefix openssl)/lib/libcrypto.dylib /usr/local/lib/
    sudo ln -s $(brew --prefix openssl)/lib/libssl.dylib  /usr/local/lib
    ```

**Comment by briansoule** [comment]
Any chance we could merge this in?

**Comment by q9f** [comment]
@se3000 🥺

**Comment by q9f** [comment]
Edit: I published https://github.com/q9f/keccak.rb as `keccak`

https://rubygems.org/gems/keccak

**Comment by q9f** [comment]
published https://github.com/q9f/ruby-eth/releases/tag/v0.4.14

as eth-patched https://rubygems.org/gems/eth-patched

**Comment by q9f** [comment]
@se3000 I'm happy to step up as co-maintainer, I just don't know the best way to reach you.

https://twitter.com/q9fmz/status/1443586096705593352
