### ISSUE TITLE
Not compatible with Ruby 3.0.2?

### ISSUE THREAD

**Issue by vasaf** [se3000/ruby-eth#71]
Just tried installing this gem, and when trying to start my server I get:

`.rbenv/versions/3.0.2/bin/ruby is loading libcrypto in an unsafe way`

**Comment by vasaf** [comment]
#67 Just noticed this mentioned here

**Comment by q9f** [comment]
Hi, thank you for your ticket.

The `eth` gem is fully compatible with Ruby 3.0.2, however there are issues on macos. See #47 

A fix is available in #66 but it's currently blocked by the `money-tree` dependency: https://github.com/GemHQ/money-tree/pull/43

**Comment by q9f** [comment]
I'm having a call with @wink (`money-tree`) later today, hopefully, we will be able to resolve this by end of the week! :)

**Comment by vasaf** [comment]
> I'm having a call with @wink (`money-tree`) later today, hopefully, we will be able to resolve this by end of the week! :)

Awesome! Thanks for the heads up 🙂
