### ISSUE TITLE
client.rb is_a? Address

### ISSUE THREAD

**Issue by ningjingzhiyuande** [se3000/ruby-eth#79]
def marshal(params)
      params = params.dup
      if params.is_a? Array
        params.map! { |param| marshal(param) }
      elsif params.is_a? Hash
        params = camelize!(params)
        params.transform_values! { |param| marshal(param) }
      elsif params.is_a? Numeric
        Util.prefix_hex "#{params.to_i.to_s(16)}"
      elsif params.is_a? Address
        params.to_s
      elsif Util.hex? params
        Util.prefix_hex params
      else
        params
      end
    end
  end

is_a? Address have issue

**Comment by q9f** [comment]
duplicate of https://github.com/q9f/eth.rb/issues/241
